### ISSUE TITLE
How to change font size using v-model after editor loaded

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [wangxiang4/vue-ace-editor#1]

**Comment by wangxiang4** [comment]
@rahulkumarsingh73690  Can be used [props option](https://github.com/wangxiang4/vue-ace-editor/blob/d6b8e04be215583bcd1df876699fa541cb2715dd/index.js#LL29C5-L29C12)

```vue
<ace-editor 
   v-model="importJson"
    lang="json"
    :options="{
      fontSize: '16px'
    }"
    theme="textmate"
    style="height: 400px;"
/>
```
If you want to have responsive control over font size you can add a value wrapping a computed
[More option config](https://github.com/ajaxorg/ace/wiki/Configuring-Ace)
